config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root :to => 'homes#top'
get 'books/new'
post 'books' => 'todolists#create'
get 'books' => 'todolists#index'
get 'books/:id' => 'todolists#show', as: 'book'
get 'books/:id/edit' => 'todolists#edit', as: 'edit_book'
patch 'books/:id' => 'todolists#update', as: 'update_books'
delete 'books/:id' => 'todolists#destroy', as: 'destroy_books'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 validates :title, presence: true
 validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top

end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def new
  	@book = Book.new
  end

  def create
        # ストロングパラメーターを使用
         @book = Book.new(book_params)
        # DBへ保存する
        if @book.save
        flash[:notice] = "successfully"
        # トップ画面へリダイレクト
        redirect_to book_path(@book.id)
        else
        flash[:notice] = "error"
        @books = Book.all
        render action: :index
       end
    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
        flash[:notice] = "successfully"
        redirect_to book_path(@book.id)
         else
        flash[:notice] = "error"
        @books = Book.all
        render action: :edit
    end
    end

    def index
    	@books = Book.all
        @book = Book.new
    end

    def show
    	@book = Book.find(params[:id])
    end

    def edit
        @book = Book.find(params[:id])
    end


    def destroy
        book = Book.find(params[:id]) #データ(レコード)を1件取得
        if book.destroy #データ（レコード）を削除
        flash[:notice] = "successfully"
        redirect_to books_path
        else
        flash[:notice] = "error"
        redirect_to books_path #List一覧画面へリダイレクト
    end
    end


  private

    def book_params
        params.require(:book).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/homes/top.html.erb
<h1>ようこそBookersへ</h1>
<p>Bookers では、さまざまな書籍に関するあなたの意見や<br>印象を共有し交換することができます</p>
<%= link_to("start","/books") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolists/edit.html.erb
 <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
<h1>編集画面</h1>
<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book' %>
<% end %>
<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/todolists/index.html.erb
 <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
 <h1>Books</h1>
   <table>
   	<tr>
   		<th>Title</th> <th>Body</th><th></th>
   	</tr>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td><td><%= book.body %></td><td><%= link_to("Show",book_path(book)) %>
      <%= link_to "Edit",edit_book_path(book) %>
      <%= link_to "Destroy",destroy_books_path(book),method: :delete,"data-confirm" => "本当に削除しますか？"%>
    </tr>
    <% end %>
  </table>


<% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h1>New book</h1>
<!-- form_for部分 -->
<%= form_for(@book, url: '/books') do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Create Book' %>

<% end %>

app/views/todolists/new.html.erb
<h1>新規投稿</h1>
<!-- form_for部分 -->
<%= form_for(@book, url: '/books') do |f| %>
 
    <h4>タイトル</h4>
    <%= f.text_field :title %>
 
    <h4>本文</h4>
    <%= f.text_area :body %>
 
    <%= f.submit '投稿' %>
 
<% end %>

app/views/todolists/show.html.erb
<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
<h2>タイトル</h2>
<p><%= @book.title %></p>
<h2>本文</h2>
<p><%= @book.body %></p>
<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", books_path %>